### ISSUE TITLE
Error caused by updating to 2.3.0

### ISSUE THREAD

**Issue by justinbmeyer** [canjs/can-reflect#109]
@Kleppo commented on [Fri May 18 2018](https://github.com/canjs/can-define/issues/336)

When I update from 2.0.3 to 2.3.0 I get this error when running my app:

`
steal.js:7977 TypeError: obj.hasOwnProperty is not a function

	    at Object.size (shape.js:1034)
	    at DefineMap.define.setup (can-define.js:985)
	    at DefineMap.setup (map.js:126)
	    at Function.newInstance (can-construct.js:289)
	    at DefineMap.init (can-construct.js:637)
	    at new DefineMap (eval at <anonymous> (can-construct.js:NaN), <anonymous>:3:32)
	    at DefineList.observable [as __type] (can-define.js:1072)
	    at DefineList.splice (list.js:527)
	    at DefineList.setup (list.js:117)
	    at Function.newInstance (can-construct.js:289)

logErrors @ steal.js:7977
tryCatchReject @ steal.js:1183
runContinuation1 @ steal.js:1142
Rejected.when @ steal.js:963
Pending.run @ steal.js:821
Scheduler._drain @ steal.js:97
Scheduler.drain @ steal.js:62
run @ steal.js:268
`

---

@justinbmeyer commented on [Fri May 18 2018](https://github.com/canjs/can-define/issues/336#issuecomment-390178571)

Thanks for reporting. I will fix this in about 3 hrs.

**Comment by justinbmeyer** [comment]
This is a bug with canReflect.size on objects that are created with out Object.prototype on their proto chain.

**Comment by Kleppo** [comment]
Thank you for the quick response! I'll test it after this weekend..
(Weekend is starting here in Belgium 😜 )
